'use client'

import { useState, useEffect } from 'react'
import {
  Card,
  CardContent,
  CardDescription,
  CardHeader,
  CardTitle
} from '@/components/ui/card'
import { Button } from '@/components/ui/button'
import { Badge } from '@/components/ui/badge'
import { Input } from '@/components/ui/input'
import { Label } from '@/components/ui/label'
import { Tabs, TabsContent, TabsList, TabsTrigger } from '@/components/ui/tabs'
import {
  Select,
  SelectContent,
  SelectItem,
  SelectTrigger,
  SelectValue,
} from '@/components/ui/select'
import {
  Dialog,
  DialogContent,
  DialogDescription,
  DialogHeader,
  DialogTitle,
  DialogTrigger,
} from '@/components/ui/dialog'
import {
  DropdownMenu,
  DropdownMenuContent,
  DropdownMenuItem,
  DropdownMenuTrigger,
} from '@/components/ui/dropdown-menu'
import { Checkbox } from '@/components/ui/checkbox'
import { Slider } from '@/components/ui/slider'
import {
  Link as LinkIcon,
  Plus,
  Search,
  MoreHorizontal,
  Edit,
  Trash2,
  ExternalLink,
  Star,
  Lightbulb,
  Tag,
  TrendingUp,
  FileText,
  ArrowRight,
  ArrowLeftRight
} from 'lucide-react'

interface Article {
  id: string
  title: string
  slug: string
  status: string
  excerpt?: string
  category: {
    id: string
    name: string
  }
}

interface RelatedArticle {
  id: string
  article: Article
  relationType: string
  isAutoGenerated: boolean
  strength: number
  createdAt: string
}

interface Suggestion {
  id: string
  title: string
  slug: string
  excerpt?: string
  tags: string[]
  category: {
    id: string
    name: string
  }
  suggestionType: string
  reason: string
  score: number
}

interface RelatedArticlesProps {
  articleId: string
}

export default function RelatedArticles({ articleId }: RelatedArticlesProps) {
  const [currentArticle, setCurrentArticle] = useState<Article | null>(null)
  const [relatedArticles, setRelatedArticles] = useState<RelatedArticle[]>([])
  const [suggestions, setSuggestions] = useState<Suggestion[]>([])
  const [allArticles, setAllArticles] = useState<Article[]>([])
  const [loading, setLoading] = useState(true)
  const [searchTerm, setSearchTerm] = useState('')
  const [addDialogOpen, setAddDialogOpen] = useState(false)
  const [editDialogOpen, setEditDialogOpen] = useState(false)
  const [selectedRelation, setSelectedRelation] = useState<RelatedArticle | null>(null)

  // Add relation state
  const [selectedArticleId, setSelectedArticleId] = useState('')
  const [relationType, setRelationType] = useState('related')
  const [bidirectional, setBidirectional] = useState(true)

  // Edit relation state
  const [editRelationType, setEditRelationType] = useState('')
  const [editStrength, setEditStrength] = useState<number[]>([0.5])

  useEffect(() => {
    fetchRelatedArticles()
    fetchAllArticles()
  }, [articleId])

  const fetchRelatedArticles = async () => {
    try {
      setLoading(true)
      const response = await fetch(`/api/admin/help/articles/${articleId}/related`)
      if (response.ok) {
        const data = await response.json()
        setCurrentArticle(data.article)
        setRelatedArticles(data.related)
        setSuggestions(data.suggestions)
      }
    } catch (error) {
      console.error('Failed to fetch related articles:', error)
    } finally {
      setLoading(false)
    }
  }

  const fetchAllArticles = async () => {
    try {
      const response = await fetch('/api/admin/help/articles')
      if (response.ok) {
        const data = await response.json()
        setAllArticles(data.articles.filter((article: Article) => article.id !== articleId))
      }
    } catch (error) {
      console.error('Failed to fetch articles:', error)
    }
  }

  const handleAddRelation = async () => {
    if (!selectedArticleId) return

    try {
      const response = await fetch(`/api/admin/help/articles/${articleId}/related`, {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({
          toArticleId: selectedArticleId,
          relationType,
          bidirectional
        })
      })

      if (response.ok) {
        await fetchRelatedArticles()
        setAddDialogOpen(false)
        setSelectedArticleId('')
        setRelationType('related')
        setBidirectional(true)
      } else {
        const error = await response.json()
        alert('Failed to add relation: ' + (error.error || 'Unknown error'))
      }
    } catch (error) {
      alert('Failed to add relation: ' + (error as Error).message)
    }
  }

  const handleEditRelation = async () => {
    if (!selectedRelation) return

    try {
      const response = await fetch(`/api/admin/help/articles/relations/${selectedRelation.id}`, {
        method: 'PUT',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({
          relationType: editRelationType,
          strength: editStrength[0]
        })
      })

      if (response.ok) {
        await fetchRelatedArticles()
        setEditDialogOpen(false)
        setSelectedRelation(null)
      } else {
        const error = await response.json()
        alert('Failed to update relation: ' + (error.error || 'Unknown error'))
      }
    } catch (error) {
      alert('Failed to update relation: ' + (error as Error).message)
    }
  }

  const handleRemoveRelation = async (relationId: string) => {
    if (!confirm('Are you sure you want to remove this relationship?')) return

    try {
      const response = await fetch(`/api/admin/help/articles/relations/${relationId}`, {
        method: 'DELETE'
      })

      if (response.ok) {
        await fetchRelatedArticles()
      } else {
        const error = await response.json()
        alert('Failed to remove relation: ' + (error.error || 'Unknown error'))
      }
    } catch (error) {
      alert('Failed to remove relation: ' + (error as Error).message)
    }
  }

  const handleAddFromSuggestion = async (suggestion: Suggestion) => {
    try {
      const response = await fetch(`/api/admin/help/articles/${articleId}/related`, {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({
          toArticleId: suggestion.id,
          relationType: 'related',
          bidirectional: true
        })
      })

      if (response.ok) {
        await fetchRelatedArticles()
      } else {
        const error = await response.json()
        alert('Failed to add relation: ' + (error.error || 'Unknown error'))
      }
    } catch (error) {
      alert('Failed to add relation: ' + (error as Error).message)
    }
  }

  const openEditDialog = (relation: RelatedArticle) => {
    setSelectedRelation(relation)
    setEditRelationType(relation.relationType)
    setEditStrength([relation.strength])
    setEditDialogOpen(true)
  }

  const getRelationTypeIcon = (type: string) => {
    switch (type) {
      case 'prerequisite':
        return <ArrowRight className="h-4 w-4" />
      case 'followup':
        return <ArrowRight className="h-4 w-4" />
      case 'alternative':
        return <ArrowLeftRight className="h-4 w-4" />
      case 'related':
      default:
        return <LinkIcon className="h-4 w-4" />
    }
  }

  const getRelationTypeColor = (type: string) => {
    switch (type) {
      case 'prerequisite':
        return 'bg-blue-100 text-blue-800'
      case 'followup':
        return 'bg-green-100 text-green-800'
      case 'alternative':
        return 'bg-purple-100 text-purple-800'
      case 'related':
      default:
        return 'bg-gray-100 text-gray-800'
    }
  }

  const getSuggestionIcon = (type: string) => {
    switch (type) {
      case 'same_category':
        return <FileText className="h-4 w-4 text-blue-600" />
      case 'common_tags':
        return <Tag className="h-4 w-4 text-green-600" />
      case 'popular':
        return <TrendingUp className="h-4 w-4 text-orange-600" />
      case 'text_similarity':
        return <Lightbulb className="h-4 w-4 text-purple-600" />
      default:
        return <Star className="h-4 w-4 text-gray-600" />
    }
  }

  const filteredArticles = allArticles.filter(article =>
    article.title.toLowerCase().includes(searchTerm.toLowerCase()) ||
    article.category.name.toLowerCase().includes(searchTerm.toLowerCase())
  )

  const filteredSuggestions = suggestions.filter(suggestion =>
    suggestion.title.toLowerCase().includes(searchTerm.toLowerCase()) ||
    suggestion.category.name.toLowerCase().includes(searchTerm.toLowerCase())
  )

  if (loading) {
    return (
      <div className="flex items-center justify-center h-96">
        <div className="animate-spin rounded-full h-8 w-8 border-b-2 border-blue-600"></div>
      </div>
    )
  }

  return (
    <div className="space-y-6">
      <div className="flex items-center justify-between">
        <div>
          <h1 className="text-2xl font-bold">Related Articles</h1>
          {currentArticle && (
            <p className="text-gray-600">Managing relationships for "{currentArticle.title}"</p>
          )}
        </div>

        <Dialog open={addDialogOpen} onOpenChange={setAddDialogOpen}>
          <DialogTrigger asChild>
            <Button className="flex items-center gap-2">
              <Plus className="h-4 w-4" />
              Add Relation
            </Button>
          </DialogTrigger>
          <DialogContent className="max-w-md">
            <DialogHeader>
              <DialogTitle>Add Related Article</DialogTitle>
              <DialogDescription>
                Create a relationship between articles
              </DialogDescription>
            </DialogHeader>

            <div className="space-y-4">
              <div>
                <Label htmlFor="search-articles">Search Articles</Label>
                <div className="relative">
                  <Search className="absolute left-3 top-3 h-4 w-4 text-gray-400" />
                  <Input
                    id="search-articles"
                    placeholder="Search articles..."
                    value={searchTerm}
                    onChange={(e) => setSearchTerm(e.target.value)}
                    className="pl-9"
                  />
                </div>
              </div>

              <div>
                <Label>Select Article</Label>
                <Select value={selectedArticleId} onValueChange={setSelectedArticleId}>
                  <SelectTrigger>
                    <SelectValue placeholder="Choose an article" />
                  </SelectTrigger>
                  <SelectContent>
                    {filteredArticles.map(article => (
                      <SelectItem key={article.id} value={article.id}>
                        <div className="flex items-center gap-2">
                          <span>{article.title}</span>
                          <Badge variant="secondary" className="text-xs">
                            {article.category.name}
                          </Badge>
                        </div>
                      </SelectItem>
                    ))}
                  </SelectContent>
                </Select>
              </div>

              <div>
                <Label>Relationship Type</Label>
                <Select value={relationType} onValueChange={setRelationType}>
                  <SelectTrigger>
                    <SelectValue />
                  </SelectTrigger>
                  <SelectContent>
                    <SelectItem value="related">Related</SelectItem>
                    <SelectItem value="prerequisite">Prerequisite</SelectItem>
                    <SelectItem value="followup">Follow-up</SelectItem>
                    <SelectItem value="alternative">Alternative</SelectItem>
                  </SelectContent>
                </Select>
              </div>

              <div className="flex items-center space-x-2">
                <Checkbox
                  id="bidirectional"
                  checked={bidirectional}
                  onCheckedChange={(checked) => setBidirectional(checked as boolean)}
                />
                <Label htmlFor="bidirectional">
                  Create bidirectional relationship
                </Label>
              </div>

              <div className="flex gap-2">
                <Button onClick={handleAddRelation} disabled={!selectedArticleId}>
                  Add Relationship
                </Button>
                <Button variant="outline" onClick={() => setAddDialogOpen(false)}>
                  Cancel
                </Button>
              </div>
            </div>
          </DialogContent>
        </Dialog>
      </div>

      <Tabs defaultValue="current" className="space-y-4">
        <TabsList>
          <TabsTrigger value="current">
            Current Relations ({relatedArticles.length})
          </TabsTrigger>
          <TabsTrigger value="suggestions">
            Suggestions ({suggestions.length})
          </TabsTrigger>
        </TabsList>

        <TabsContent value="current" className="space-y-4">
          {relatedArticles.length === 0 ? (
            <Card>
              <CardContent className="flex flex-col items-center justify-center py-12">
                <LinkIcon className="h-12 w-12 text-gray-400 mb-4" />
                <h3 className="text-lg font-semibold text-gray-900 mb-2">No Related Articles</h3>
                <p className="text-gray-600 text-center mb-4">
                  This article doesn't have any related articles yet. Add some to help users discover related content.
                </p>
                <Button onClick={() => setAddDialogOpen(true)} className="flex items-center gap-2">
                  <Plus className="h-4 w-4" />
                  Add First Relation
                </Button>
              </CardContent>
            </Card>
          ) : (
            <div className="grid gap-4">
              {relatedArticles.map((relation) => (
                <Card key={relation.id}>
                  <CardContent className="p-6">
                    <div className="flex items-start justify-between">
                      <div className="flex-1">
                        <div className="flex items-center gap-3 mb-2">
                          <h3 className="font-semibold text-lg">{relation.article.title}</h3>
                          <Badge
                            variant="secondary"
                            className={getRelationTypeColor(relation.relationType)}
                          >
                            <div className="flex items-center gap-1">
                              {getRelationTypeIcon(relation.relationType)}
                              {relation.relationType}
                            </div>
                          </Badge>
                          {relation.isAutoGenerated && (
                            <Badge variant="outline" className="text-xs">
                              Auto
                            </Badge>
                          )}
                        </div>

                        <div className="flex items-center gap-4 text-sm text-gray-600 mb-3">
                          <span>Category: {relation.article.category.name}</span>
                          <span>Status: {relation.article.status}</span>
                          <span>Strength: {(relation.strength * 100).toFixed(0)}%</span>
                        </div>

                        {relation.article.excerpt && (
                          <p className="text-gray-700 mb-3">{relation.article.excerpt}</p>
                        )}

                        <div className="flex items-center gap-2">
                          <Button
                            variant="outline"
                            size="sm"
                            className="flex items-center gap-1"
                            onClick={() => window.open(`/help/${relation.article.slug}`, '_blank')}
                          >
                            <ExternalLink className="h-3 w-3" />
                            View
                          </Button>
                        </div>
                      </div>

                      <DropdownMenu>
                        <DropdownMenuTrigger asChild>
                          <Button variant="ghost" size="sm">
                            <MoreHorizontal className="h-4 w-4" />
                          </Button>
                        </DropdownMenuTrigger>
                        <DropdownMenuContent align="end">
                          <DropdownMenuItem onClick={() => openEditDialog(relation)}>
                            <Edit className="h-4 w-4 mr-2" />
                            Edit Relationship
                          </DropdownMenuItem>
                          <DropdownMenuItem
                            onClick={() => handleRemoveRelation(relation.id)}
                            className="text-red-600"
                          >
                            <Trash2 className="h-4 w-4 mr-2" />
                            Remove Relationship
                          </DropdownMenuItem>
                        </DropdownMenuContent>
                      </DropdownMenu>
                    </div>
                  </CardContent>
                </Card>
              ))}
            </div>
          )}
        </TabsContent>

        <TabsContent value="suggestions" className="space-y-4">
          <div className="flex items-center gap-4 mb-4">
            <div className="relative flex-1">
              <Search className="absolute left-3 top-3 h-4 w-4 text-gray-400" />
              <Input
                placeholder="Search suggestions..."
                value={searchTerm}
                onChange={(e) => setSearchTerm(e.target.value)}
                className="pl-9"
              />
            </div>
          </div>

          {filteredSuggestions.length === 0 ? (
            <Card>
              <CardContent className="flex flex-col items-center justify-center py-12">
                <Lightbulb className="h-12 w-12 text-gray-400 mb-4" />
                <h3 className="text-lg font-semibold text-gray-900 mb-2">No Suggestions Available</h3>
                <p className="text-gray-600 text-center">
                  No related article suggestions found based on content, tags, or category.
                </p>
              </CardContent>
            </Card>
          ) : (
            <div className="grid gap-4">
              {filteredSuggestions.map((suggestion) => (
                <Card key={suggestion.id}>
                  <CardContent className="p-6">
                    <div className="flex items-start justify-between">
                      <div className="flex-1">
                        <div className="flex items-center gap-3 mb-2">
                          <h3 className="font-semibold text-lg">{suggestion.title}</h3>
                          <Badge variant="secondary">
                            {suggestion.category.name}
                          </Badge>
                          <div className="flex items-center gap-1 text-sm text-gray-600">
                            {getSuggestionIcon(suggestion.suggestionType)}
                            <span>{(suggestion.score * 100).toFixed(0)}% match</span>
                          </div>
                        </div>

                        <p className="text-sm text-gray-600 mb-3">{suggestion.reason}</p>

                        {suggestion.excerpt && (
                          <p className="text-gray-700 mb-3">{suggestion.excerpt}</p>
                        )}

                        {suggestion.tags && suggestion.tags.length > 0 && (
                          <div className="flex items-center gap-2 mb-3">
                            <Tag className="h-4 w-4 text-gray-400" />
                            <div className="flex gap-1">
                              {suggestion.tags.slice(0, 3).map((tag, index) => (
                                <Badge key={index} variant="outline" className="text-xs">
                                  {tag}
                                </Badge>
                              ))}
                              {suggestion.tags.length > 3 && (
                                <span className="text-xs text-gray-500">
                                  +{suggestion.tags.length - 3} more
                                </span>
                              )}
                            </div>
                          </div>
                        )}

                        <div className="flex items-center gap-2">
                          <Button
                            onClick={() => handleAddFromSuggestion(suggestion)}
                            size="sm"
                            className="flex items-center gap-1"
                          >
                            <Plus className="h-3 w-3" />
                            Add Relation
                          </Button>
                          <Button
                            variant="outline"
                            size="sm"
                            className="flex items-center gap-1"
                            onClick={() => window.open(`/help/${suggestion.slug}`, '_blank')}
                          >
                            <ExternalLink className="h-3 w-3" />
                            View
                          </Button>
                        </div>
                      </div>
                    </div>
                  </CardContent>
                </Card>
              ))}
            </div>
          )}
        </TabsContent>
      </Tabs>

      {/* Edit Relationship Dialog */}
      <Dialog open={editDialogOpen} onOpenChange={setEditDialogOpen}>
        <DialogContent className="max-w-md">
          <DialogHeader>
            <DialogTitle>Edit Relationship</DialogTitle>
            <DialogDescription>
              Modify the relationship type and strength
            </DialogDescription>
          </DialogHeader>

          {selectedRelation && (
            <div className="space-y-4">
              <div>
                <Label>Article: {selectedRelation.article.title}</Label>
              </div>

              <div>
                <Label>Relationship Type</Label>
                <Select value={editRelationType} onValueChange={setEditRelationType}>
                  <SelectTrigger>
                    <SelectValue />
                  </SelectTrigger>
                  <SelectContent>
                    <SelectItem value="related">Related</SelectItem>
                    <SelectItem value="prerequisite">Prerequisite</SelectItem>
                    <SelectItem value="followup">Follow-up</SelectItem>
                    <SelectItem value="alternative">Alternative</SelectItem>
                  </SelectContent>
                </Select>
              </div>

              <div>
                <Label>Relationship Strength: {(editStrength[0] * 100).toFixed(0)}%</Label>
                <Slider
                  value={editStrength}
                  onValueChange={setEditStrength}
                  max={1}
                  min={0}
                  step={0.1}
                  className="mt-2"
                />
              </div>

              <div className="flex gap-2">
                <Button onClick={handleEditRelation}>
                  Update Relationship
                </Button>
                <Button variant="outline" onClick={() => setEditDialogOpen(false)}>
                  Cancel
                </Button>
              </div>
            </div>
          )}
        </DialogContent>
      </Dialog>
    </div>
  )
}