/**
 * Playwright global teardown.
 *
 * Intentionally minimal: the e2e fixtures are idempotent upserts owned by
 * prisma/seed-e2e.ts (never deleted between runs), and the storage state in
 * e2e/.auth/ is regenerated by every global-setup run (and gitignored), so
 * there is nothing that must be cleaned up here.
 */
async function globalTeardown() {
  console.log('🧹 e2e global teardown — nothing to clean up (fixtures are idempotent)')
}

export default globalTeardown
