import { NextRequest, NextResponse } from 'next/server'
import { requireAdmin } from '@/lib/auth'
import { handleApiError } from '@/lib/api/respond'
import { prisma } from '@/lib/prisma'
interface RouteParams {
  params: Promise<{
    id: string
  }>
}

// DELETE /api/admin/help/articles/relations/[id] - Remove article relationship
export async function DELETE(request: NextRequest, props: RouteParams) {
  const params = await props.params;
  try {
    await requireAdmin()

    const { id: relationId } = params

    // Get the relationship to be deleted
    const relation = await prisma.helpArticleRelation.findUnique({
      where: { id: relationId }
    })

    if (!relation) {
      return NextResponse.json({ error: 'Relationship not found' }, { status: 404 })
    }

    // Check if there's a bidirectional relationship to also remove
    const reverseRelation = await prisma.helpArticleRelation.findFirst({
      where: {
        fromArticleId: relation.toArticleId,
        toArticleId: relation.fromArticleId,
        isAutoGenerated: relation.isAutoGenerated
      }
    })

    // Delete the relationship(s)
    await prisma.helpArticleRelation.delete({
      where: { id: relationId }
    })

    if (reverseRelation) {
      await prisma.helpArticleRelation.delete({
        where: { id: reverseRelation.id }
      })
    }

    return NextResponse.json({
      message: 'Relationship removed successfully'
    })
  } catch (error) {
    return handleApiError(error)
  }
}

// PUT /api/admin/help/articles/relations/[id] - Update article relationship
export async function PUT(request: NextRequest, props: RouteParams) {
  const params = await props.params;
  try {
    await requireAdmin()

    const { id: relationId } = params
    const { relationType, strength } = await request.json()

    // Validate the relationship exists
    const existingRelation = await prisma.helpArticleRelation.findUnique({
      where: { id: relationId }
    })

    if (!existingRelation) {
      return NextResponse.json({ error: 'Relationship not found' }, { status: 404 })
    }

    // Update the relationship
    const updatedRelation = await prisma.helpArticleRelation.update({
      where: { id: relationId },
      data: {
        ...(relationType && { relationType }),
        ...(typeof strength === 'number' && { strength: Math.max(0, Math.min(1, strength)) }),
        updatedAt: new Date()
      },
      include: {
        fromArticle: {
          select: {
            id: true,
            title: true,
            slug: true
          }
        },
        toArticle: {
          select: {
            id: true,
            title: true,
            slug: true,
            status: true,
            excerpt: true,
            category: {
              select: {
                id: true,
                name: true
              }
            }
          }
        }
      }
    })

    // Update reverse relationship if it exists
    if (relationType || typeof strength === 'number') {
      const reverseRelation = await prisma.helpArticleRelation.findFirst({
        where: {
          fromArticleId: existingRelation.toArticleId,
          toArticleId: existingRelation.fromArticleId
        }
      })

      if (reverseRelation) {
        await prisma.helpArticleRelation.update({
          where: { id: reverseRelation.id },
          data: {
            ...(relationType && { relationType }),
            ...(typeof strength === 'number' && { strength: Math.max(0, Math.min(1, strength)) }),
            updatedAt: new Date()
          }
        })
      }
    }

    return NextResponse.json({
      message: 'Relationship updated successfully',
      relation: updatedRelation
    })
  } catch (error) {
    return handleApiError(error)
  }
}