import { NextRequest, NextResponse } from 'next/server'
import { getServerSession } from 'next-auth/next'
import { authOptions } from '@/lib/auth/config'
import { prisma } from '@/lib/prisma'
import { normalizeUserId } from '@/lib/auth/demo-user'

interface RouteParams {
  params: {
    id: string
  }
}

// DELETE /api/admin/help/articles/relations/[id] - Remove article relationship
export async function DELETE(request: NextRequest, { params }: RouteParams) {
  try {
    // Check authentication and admin permissions
    const session = await getServerSession(authOptions)
    if (!session?.user?.id) {
      return NextResponse.json({ error: 'Unauthorized' }, { status: 401 })
    }

    const userId = normalizeUserId(session.user.id)

    // Verify user has admin permissions
    const userWorkspaces = await prisma.userWorkspace.findMany({
      where: {
        userId,
        role: { in: ['OWNER', 'ADMIN'] }
      }
    })

    if (userWorkspaces.length === 0) {
      return NextResponse.json({ error: 'Forbidden' }, { status: 403 })
    }

    const { id: relationId } = params

    // Get the relationship to be deleted
    const relation = await prisma.helpArticleRelation.findUnique({
      where: { id: relationId }
    })

    if (!relation) {
      return NextResponse.json({ error: 'Relationship not found' }, { status: 404 })
    }

    // Check if there's a bidirectional relationship to also remove
    const reverseRelation = await prisma.helpArticleRelation.findFirst({
      where: {
        fromArticleId: relation.toArticleId,
        toArticleId: relation.fromArticleId,
        isAutoGenerated: relation.isAutoGenerated
      }
    })

    // Delete the relationship(s)
    await prisma.helpArticleRelation.delete({
      where: { id: relationId }
    })

    if (reverseRelation) {
      await prisma.helpArticleRelation.delete({
        where: { id: reverseRelation.id }
      })
    }

    return NextResponse.json({
      message: 'Relationship removed successfully'
    })
  } catch (error) {
    console.error('Failed to remove relationship:', error)
    return NextResponse.json(
      { error: 'Failed to remove relationship' },
      { status: 500 }
    )
  }
}

// PUT /api/admin/help/articles/relations/[id] - Update article relationship
export async function PUT(request: NextRequest, { params }: RouteParams) {
  try {
    // Check authentication and admin permissions
    const session = await getServerSession(authOptions)
    if (!session?.user?.id) {
      return NextResponse.json({ error: 'Unauthorized' }, { status: 401 })
    }

    const userId = normalizeUserId(session.user.id)

    // Verify user has admin permissions
    const userWorkspaces = await prisma.userWorkspace.findMany({
      where: {
        userId,
        role: { in: ['OWNER', 'ADMIN'] }
      }
    })

    if (userWorkspaces.length === 0) {
      return NextResponse.json({ error: 'Forbidden' }, { status: 403 })
    }

    const { id: relationId } = params
    const { relationType, strength } = await request.json()

    // Validate the relationship exists
    const existingRelation = await prisma.helpArticleRelation.findUnique({
      where: { id: relationId }
    })

    if (!existingRelation) {
      return NextResponse.json({ error: 'Relationship not found' }, { status: 404 })
    }

    // Update the relationship
    const updatedRelation = await prisma.helpArticleRelation.update({
      where: { id: relationId },
      data: {
        ...(relationType && { relationType }),
        ...(typeof strength === 'number' && { strength: Math.max(0, Math.min(1, strength)) }),
        updatedAt: new Date()
      },
      include: {
        fromArticle: {
          select: {
            id: true,
            title: true,
            slug: true
          }
        },
        toArticle: {
          select: {
            id: true,
            title: true,
            slug: true,
            status: true,
            excerpt: true,
            category: {
              select: {
                id: true,
                name: true
              }
            }
          }
        }
      }
    })

    // Update reverse relationship if it exists
    if (relationType || typeof strength === 'number') {
      const reverseRelation = await prisma.helpArticleRelation.findFirst({
        where: {
          fromArticleId: existingRelation.toArticleId,
          toArticleId: existingRelation.fromArticleId
        }
      })

      if (reverseRelation) {
        await prisma.helpArticleRelation.update({
          where: { id: reverseRelation.id },
          data: {
            ...(relationType && { relationType }),
            ...(typeof strength === 'number' && { strength: Math.max(0, Math.min(1, strength)) }),
            updatedAt: new Date()
          }
        })
      }
    }

    return NextResponse.json({
      message: 'Relationship updated successfully',
      relation: updatedRelation
    })
  } catch (error) {
    console.error('Failed to update relationship:', error)
    return NextResponse.json(
      { error: 'Failed to update relationship' },
      { status: 500 }
    )
  }
}