# Kubernetes CronJob for automated backups

apiVersion: batch/v1
kind: CronJob
metadata:
  name: postgres-backup
  namespace: sociallyhub
spec:
  schedule: "0 2 * * *"  # Daily at 2 AM
  jobTemplate:
    spec:
      template:
        spec:
          restartPolicy: OnFailure
          containers:
          - name: postgres-backup
            image: postgres:15-alpine
            command: ["/bin/sh"]
            args: ["/scripts/postgres-backup.sh"]
            env:
            - name: POSTGRES_HOST
              value: "postgres-service"
            - name: POSTGRES_USER
              value: "sociallyhub"
            - name: POSTGRES_DB
              value: "sociallyhub"
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: POSTGRES_PASSWORD
            - name: BACKUP_DIR
              value: "/backups"
            - name: S3_BUCKET
              valueFrom:
                configMapKeyRef:
                  name: backup-config
                  key: S3_BUCKET
                  optional: true
            - name: WEBHOOK_URL
              valueFrom:
                secretKeyRef:
                  name: backup-secrets
                  key: WEBHOOK_URL
                  optional: true
            volumeMounts:
            - name: backup-scripts
              mountPath: /scripts
            - name: backup-storage
              mountPath: /backups
            resources:
              requests:
                memory: "128Mi"
                cpu: "100m"
              limits:
                memory: "256Mi"
                cpu: "200m"
          volumes:
          - name: backup-scripts
            configMap:
              name: backup-scripts
              defaultMode: 0755
          - name: backup-storage
            persistentVolumeClaim:
              claimName: backup-pvc
---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: redis-backup
  namespace: sociallyhub
spec:
  schedule: "0 3 * * *"  # Daily at 3 AM
  jobTemplate:
    spec:
      template:
        spec:
          restartPolicy: OnFailure
          containers:
          - name: redis-backup
            image: redis:7-alpine
            command: ["/bin/sh"]
            args: ["/scripts/redis-backup.sh"]
            env:
            - name: REDIS_HOST
              value: "redis-service"
            - name: REDIS_PORT
              value: "6379"
            - name: REDIS_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: redis-secret
                  key: REDIS_PASSWORD
            - name: BACKUP_DIR
              value: "/backups"
            - name: S3_BUCKET
              valueFrom:
                configMapKeyRef:
                  name: backup-config
                  key: S3_BUCKET
                  optional: true
            - name: WEBHOOK_URL
              valueFrom:
                secretKeyRef:
                  name: backup-secrets
                  key: WEBHOOK_URL
                  optional: true
            volumeMounts:
            - name: backup-scripts
              mountPath: /scripts
            - name: backup-storage
              mountPath: /backups
            resources:
              requests:
                memory: "64Mi"
                cpu: "50m"
              limits:
                memory: "128Mi"
                cpu: "100m"
          volumes:
          - name: backup-scripts
            configMap:
              name: backup-scripts
              defaultMode: 0755
          - name: backup-storage
            persistentVolumeClaim:
              claimName: backup-pvc
---
# ConfigMap for backup configuration
apiVersion: v1
kind: ConfigMap
metadata:
  name: backup-config
  namespace: sociallyhub
data:
  RETENTION_DAYS: "7"
  S3_BUCKET: "sociallyhub-backups"  # Optional: set to your S3 bucket
---
# Secret for backup webhook and AWS credentials
apiVersion: v1
kind: Secret
metadata:
  name: backup-secrets
  namespace: sociallyhub
type: Opaque
data:
  # Base64 encoded values
  WEBHOOK_URL: ""  # Optional: Slack webhook for notifications
  AWS_ACCESS_KEY_ID: ""  # Optional: for S3 uploads
  AWS_SECRET_ACCESS_KEY: ""  # Optional: for S3 uploads
---
# ConfigMap containing backup scripts
apiVersion: v1
kind: ConfigMap
metadata:
  name: backup-scripts
  namespace: sociallyhub
data:
  postgres-backup.sh: |
    # The postgres-backup.sh script content goes here
    # (This would be the full script from the previous file)
  redis-backup.sh: |
    # The redis-backup.sh script content goes here
    # (This would be the full script from the previous file)
---
# PVC for backup storage
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: backup-pvc
  namespace: sociallyhub
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 50Gi
  storageClassName: standard