// Public share-link API (ADR-0020 Phase 1 item 4) — GET renders the frozen
// snapshot payload, POST verifies an optional password.
//
// SECURITY INVARIANTS (do not weaken):
// - Anonymous by design: this file never imports the auth module ('@/lib/auth',
//   next-auth) — enforced by an eslint zone. Access is declared 'public' via
//   withApiAuth, which also applies the per-IP rate limit (ADR-0005).
// - Uniform 404: only resolveUsableShareLink() decides usability; unknown,
//   malformed, expired, and revoked tokens all get the identical
//   jsonError(404, 'Not found') — no oracle.
// - Snapshot-only: responses are built exclusively from ClientReport.data and
//   ClientBranding; no live analytics queries.
// - The raw token is never logged and never stored; proof of password
//   verification is a short-lived HMAC-signed HttpOnly cookie, not a session.

import { NextResponse, type NextRequest } from 'next/server'

import { withApiAuth } from '@/lib/api/with-api-auth'
import { jsonError } from '@/lib/api/respond'
import { prisma } from '@/lib/prisma'
import {
  createShareAccessCookieValue,
  resolveUsableShareLink,
  shareAccessCookieName,
  SHARE_ACCESS_COOKIE_TTL_SECONDS,
  verifyShareAccessCookieValue,
  verifySharePassword,
} from '@/lib/sharing/report-share'

import type { ClientBranding } from '@prisma/client'
import type { ReportBrandingProps } from '@/components/reports/report-snapshot-view'

const SHAREABLE_STATUSES = new Set(['COMPLETED', 'SENT'])

const RATE_LIMIT = { key: 'ip', points: 30, windowSec: 60 } as const

// Next 15.5's generated route validators (.next/types) require the exported
// handler's second parameter to be exactly `{ params: Promise<...> }`.
// withApiAuth returns a wider `NextRouteContext<P>` ({ params?: Promise<P> | P }),
// which is assignable to this narrower signature by parameter contravariance —
// the annotation is a pure type narrowing with no runtime effect, and it keeps
// `tsc --noEmit` green when .next/types has been generated by a dev/build run.
type RouteHandler = (
  request: NextRequest,
  ctx: { params: Promise<{ token: string }> }
) => Promise<NextResponse>

function toBrandingProps(row: ClientBranding | null): ReportBrandingProps | null {
  if (!row) return null
  return {
    title: row.title,
    logoUrl: row.logoUrl,
    primaryColor: row.primaryColor,
    accentColor: row.accentColor,
    hideCredits: row.hideCredits,
  }
}

/**
 * GET /api/share/reports/[token]
 * - unusable token → uniform 404
 * - password set + no valid access cookie → 200 { passwordRequired: true }
 *   (counters NOT incremented)
 * - else → 200 { passwordRequired: false, report, data, branding } and
 *   increments viewCount / lastAccessedAt (the only path that counts).
 */
export const GET: RouteHandler = withApiAuth<{ token: string }>(
  async (request: NextRequest, { params }) => {
    const link = await resolveUsableShareLink(params.token)
    if (!link) return jsonError(404, 'Not found')

    if (link.passwordHash) {
      const cookieValue = request.cookies.get(
        shareAccessCookieName(link.tokenHash)
      )?.value
      if (!verifyShareAccessCookieValue(cookieValue, link.id)) {
        return NextResponse.json({ passwordRequired: true })
      }
    }

    const report = await prisma.clientReport.findUnique({
      where: { id: link.reportId },
      include: { client: { select: { name: true } } },
    })
    // A link whose report lost its shareable snapshot is as good as unusable —
    // keep the response indistinguishable from an unknown token.
    if (!report || !SHAREABLE_STATUSES.has(report.status) || report.data == null) {
      return jsonError(404, 'Not found')
    }

    const brandingRow = await prisma.clientBranding.findUnique({
      where: { workspaceId: link.workspaceId },
    })

    await prisma.reportShareLink.update({
      where: { id: link.id },
      data: { viewCount: { increment: 1 }, lastAccessedAt: new Date() },
    })

    return NextResponse.json({
      passwordRequired: false,
      report: {
        name: report.name,
        type: report.type,
        clientName: report.client.name,
        generatedAt: report.lastGenerated?.toISOString() ?? null,
        description: report.description,
        frequency: report.frequency,
      },
      data: report.data,
      branding: toBrandingProps(brandingRow),
    })
  },
  { access: 'public', limit: RATE_LIMIT }
)

/**
 * POST /api/share/reports/[token]  body: { password }
 * - unusable token → uniform 404
 * - link has no password → 400
 * - wrong password → 401 'Invalid password'
 * - correct → 200 { success: true } + short-lived HMAC-signed HttpOnly cookie
 */
export const POST: RouteHandler = withApiAuth<{ token: string }>(
  async (request: NextRequest, { params }) => {
    const link = await resolveUsableShareLink(params.token)
    if (!link) return jsonError(404, 'Not found')

    if (!link.passwordHash) {
      return jsonError(400, 'This link does not require a password')
    }

    let password: unknown
    try {
      const body = (await request.json()) as { password?: unknown } | null
      password = body?.password
    } catch {
      password = undefined
    }
    if (typeof password !== 'string' || password.length === 0) {
      return jsonError(400, 'Password is required')
    }

    const valid = await verifySharePassword(password, link.passwordHash)
    if (!valid) return jsonError(401, 'Invalid password')

    const res = NextResponse.json({ success: true })
    res.cookies.set(
      shareAccessCookieName(link.tokenHash),
      createShareAccessCookieValue(link.id),
      {
        httpOnly: true,
        sameSite: 'lax',
        path: '/',
        maxAge: SHARE_ACCESS_COOKIE_TTL_SECONDS,
        secure: process.env.NODE_ENV === 'production',
      }
    )
    return res
  },
  { access: 'public', limit: RATE_LIMIT }
)
